### PR TITLE
Reduced the docker image size to only 645MB & speeded up the image bu…

### PR DESCRIPTION
**Pull request by mimusica**
Reduced the docker image size from 1.12Gb to only 645MB & increased the speed of the image build process by n (n= number of cpu cores on your machine).

image

### CODE REVIEW

**Comment by mimusica** [comment]
modified the dockerfiles for asterisk 11, 13 & 14.

**Comment by mimusica** [comment]
11 & 13 ended OK

only 14 is still hanging atm

**Comment by mimusica** [comment]
added a Dockerfile for asterisk 16 certified LTS & added tests for it in travis.yml

**Comment by dougbtv** [comment]
LGTM, thanks for the contribution @mimusica !

**Comment by mimusica** [comment]
You're welcome.

I've just sent you a new pull request with my latest commit.

BTW do you know about any possible job opportunities for me?

Kind regards,

Christophe Langenberg

Op vr 24 jul. 2020 16:33 schreef Doug Smith <notifications@github.com>:

**Pull request merged**
