### PR TITLE
Did some more modifications

### LINKED ISSUE #71: Docker image too big
Hello,

At the moment the image is very big because as you build the source you are never removing the build packages that you've installed and never gonna be used anymore.

Its over 1 gb non compressed

Can you please uninstall them after you're done with building so you can decrease the size of your image, thanks!

### PR DESCRIPTION
**Pull request by mimusica**
removed Astrisk 14 standard --> already over it's EOL
downsized the Astrisk 16 image some more
image
.travis.yml --> removed all tests related to Astrisk 14
README.md --> replaced all entries of Astrisk 14 with Astrisk 16

Now travis-ci shouldn't fail anymore

Fixes #71

### CODE REVIEW

**Comment by mimusica** [comment]
@dougbtv 
I guess you can close the topic below:
https://github.com/dougbtv/docker-asterisk/issues/71

**Comment by mimusica** [comment]
BTW do you happen to know why GitHub doesn't mention me as a contributor?

**Comment by mimusica** [comment]
:1st_place_medal:

**Comment by dougbtv** [comment]
Thanks for fixing this up!

**Pull request merged**
